#!/bin/bash

echo "🚀 Deploying NebulaFlow Backend to Render..."

echo ""
echo "📋 Manual Deployment Steps for Render:"
echo ""
echo "1. Go to https://render.com"
echo "2. Sign up/Login with your GitHub account"
echo "3. Click 'New Web Service'"
echo "4. Connect your GitHub repository:"
echo "   https://github.com/YasirAhmedGHauri/nebulaflow-markdown-editor.git"
echo ""
echo "5. Configure the service:"
echo "   • Name: nebulaflow-backend"
echo "   • Root Directory: server"
echo "   • Build Command: npm install"
echo "   • Start Command: npm start"
echo "   • Plan: Free"
echo ""
echo "6. Add Environment Variables:"
echo "   • NODE_ENV: production"
echo "   • CORS_ORIGIN: https://nebulaflow-markdown-editor-qgfj0jhrm-yasirahmedghauris-projects.vercel.app"
echo ""
echo "7. Click 'Create Web Service'"
echo ""
echo "8. After deployment, copy the URL and update your frontend:"
echo "   • Go to your Vercel project settings"
echo "   • Add environment variable:"
echo "     REACT_APP_API_URL=https://your-backend-url.onrender.com"
echo ""
echo "🎉 Your full application will be live!"
echo ""
echo "Frontend: https://nebulaflow-markdown-editor-qgfj0jhrm-yasirahmedghauris-projects.vercel.app"
echo "Backend: https://your-backend-url.onrender.com"
