#!/bin/bash

echo "🚀 Deploying NebulaFlow to GitHub Pages..."

echo ""
echo "📋 GitHub Pages Deployment Steps:"
echo ""
echo "1. ✅ GitHub Actions workflow created"
echo "2. ✅ Homepage configured in package.json"
echo ""
echo "3. 🔧 Enable GitHub Pages in your repository:"
echo "   • Go to: https://github.com/YasirAhmedGHauri/nebulaflow-markdown-editor/settings/pages"
echo "   • Source: Deploy from a branch"
echo "   • Branch: gh-pages"
echo "   • Folder: / (root)"
echo "   • Click 'Save'"
echo ""
echo "4. 🔄 Push changes to trigger deployment:"
echo "   git add ."
echo "   git commit -m 'Configure GitHub Pages deployment'"
echo "   git push origin main"
echo ""
echo "5. 🌐 Your app will be available at:"
echo "   https://yasirahmedghauri.github.io/nebulaflow-markdown-editor"
echo ""
echo "6. 📝 Note: Backend API will need to be deployed separately"
echo "   (GitHub Pages only hosts static files)"
echo ""
echo "🎉 After deployment, your frontend will be live on GitHub Pages!"
